#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login:
  path: /login
  controller: App\Controller\SecurityController::login

change_password:
  path: /change/password
  controller: App\Controller\ChangePasswordController::index
